# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
import numpy as np
array = np.arange(10).reshape(2,5)
print(array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

---



---


In [ ]:
arry1 = np.arange(10).reshape(2,5)
print(arry1)
arry2 = np.ones(10).reshape(2,5)
print(arry2)
np.vstack((arry1,arry2))


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [ ]:
ary1 = [0, 1, 2, 3, 4, 1, 1, 1, 1, 1]
ary2 = [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]
np.hstack((ary1,ary2))

array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [ ]:
arry = np.arange(15).reshape(3,5)
print(arry)
np.ravel(arry)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

array([[ 0, 1, 2],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])

In [ ]:
ary = np.arange(15)
print(ary)
ary.reshape(5,3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [ ]:
array = np.arange(25).reshape(5,5)
print(array)
print("---------------------------------------")
square_array = np.square(array)
print(square_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
---------------------------------------
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [ ]:
my_array = np.arange(30).reshape(5,6)
print(my_array)
print("--------------------------")
mean_array = np.mean(my_array)
print("Mean of the Array",mean_array)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
--------------------------
Mean of the Array 14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [ ]:
std_array = np.std(my_array)
print("standard deviation of the  Q8: ",std_array)

standard deviation of the  Q8:  8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [ ]:
median_array = np.median(my_array)
print("Median of the  Q8: ",median_array)

Median of the  Q8:  14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [ ]:
transpose_array = np.transpose(my_array)
print("transpose of the  Q8: ",transpose_array)

transpose of the  Q8:  [[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [ ]:
My_array = np.arange(16).reshape(4,4)
print(My_array)
print("--------------------------")
diagonal_array = np.diagonal(My_array)
print(diagonal_array)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
--------------------------
[ 0  5 10 15]


## Question:13

### Find the determinant of the previous array in Q12?

In [ ]:
det_array = np.linalg.det(My_array)
print("Determinant of the previous array in Q12: ",det_array)

Determinant of the previous array in Q12:  0.0


## Question:14

### Find the 5th and 95th percentile of an array?

In [ ]:
array = np.arange(10)
print(array)
print("5th percentile of arr : ",np.percentile(array, 5))
print("------------------------------------------------")
print("95th percentile of arr : ",np.percentile(array,95))

[0 1 2 3 4 5 6 7 8 9]
5th percentile of arr :  0.45
------------------------------------------------
95th percentile of arr :  8.549999999999999


## Question:15

### How to find if a given array has any null values?

In [ ]:
new_array = np.array([0,1,2,3,4,NaN,6,7,8])
print(new_array)
print("---------------------------------------------------------")


NameError: ignored