# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [4]:
vector = np.arange(10,49)
print("Original vector:")
print(vector)

Original vector:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


4. Find the shape of previous array in question 3

In [5]:
print(vector.shape)

(39,)


5. Print the type of the previous array in question 3

In [6]:
print(type(x))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration





In [7]:
print(np.version)
print(np.show_config())

<module 'numpy.version' from '/usr/local/lib/python3.6/dist-packages/numpy/version.py'>
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [8]:
dimension = np.shape(vector)
print(dimension)


(39,)


8. Create a boolean array with all the True values

In [9]:
bool_arr = np.ones(10, dtype=bool)
print(bool_arr)

[ True  True  True  True  True  True  True  True  True  True]


9. Create a two dimensional array




In [10]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


10. Create a three dimensional array



In [11]:
array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[11,12,13,14,15]])
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [12]:
i = np.arange(15, 40)
print(i)
i = i[::-1]
print(i)



[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39]
[39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16
 15]


12. Create a null vector of size 10 but the fifth value which is 1 

In [13]:
y = np.zeros(10)
y[5] = 1
print(y)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


 Create a 3x3 identity matrix

In [14]:
array_2D=np.identity(3)
print(array_2D)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [15]:
arr = np.array([1,2,3,4,5], dtype='bool')


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [16]:
arr1 = np.array([[1.,2.,3.],[4.,5.,6.]])
arr2 = np.array([[0.,4.,1.],[1.,2.,12]])
arr3 = arr1 * arr2
print(arr3)


[[ 0.  8.  3.]
 [ 4. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [17]:
arry1 = np.array([[1.,2.,3.],[4.,5.,6.]])
arry2 = np.array([[0.,4.,1.],[7.,2.,12]])
comparison  = arry1 == arry2
result = comparison.all()
print(result)

False


17. Extract all odd numbers from arr with values(0-9)

In [45]:
x = np.arange(10)
x[x % 2 == 1]


array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [46]:
x [x % 2 == 1] = -1
x

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [43]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
j = np.ones((5,5))
j[1:-1,1:-1] = 0
print(j)



[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [42]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[:] = 12
arr2d[1:2,1:2] = 5
arr2d


array([[12, 12, 12],
       [12,  5, 12],
       [12, 12, 12]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [41]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [40]:
arr_2d = np.arange(10).reshape(2,5)
print(arr_2d)
arr_2d[0:1,:]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 1, 2, 3, 4]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [39]:
arr_2d = np.arange(10).reshape(2,5)
print(arr_2d)
arr_2d[1:2,1:2]


[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[6]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [38]:
arr_2d = np.arange(10).reshape(2,5)
print(arr_2d)
arr_2d[:, 2:3]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [37]:
rand_arr = np.random.rand(100).reshape(10,10)
print('orignal array is')
print(rand_arr)
print('min value is',rand_arr.min())
print('max value is',rand_arr.max())


orignal array is
[[0.37860247 0.84232848 0.3196116  0.80229969 0.95618601 0.97799311
  0.67729444 0.14795836 0.13646094 0.05190399]
 [0.69187688 0.23035623 0.94439815 0.37986981 0.66885815 0.46667948
  0.0942005  0.36131868 0.24293321 0.05574784]
 [0.81616488 0.80677415 0.27524832 0.65163405 0.97109465 0.72509467
  0.426539   0.59458195 0.52675602 0.18427302]
 [0.41243955 0.11158537 0.49389875 0.56233498 0.80815705 0.69388759
  0.18473956 0.3710097  0.31619728 0.23937096]
 [0.51309444 0.78558643 0.1571331  0.8061015  0.80045847 0.50059095
  0.75974037 0.15546646 0.06221735 0.48593393]
 [0.23515484 0.68131888 0.1041489  0.60525261 0.69775264 0.03391079
  0.74781004 0.24111655 0.83538845 0.24097713]
 [0.10863484 0.97918241 0.30256148 0.28965964 0.49707105 0.92870488
  0.39470632 0.42726323 0.70209193 0.95017487]
 [0.04532317 0.37417458 0.07380091 0.22377077 0.41122003 0.55949084
  0.30670487 0.29127204 0.36240187 0.06915263]
 [0.62279653 0.8790667  0.3750619  0.1184794  0.71459335 0.5299

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [22]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b)) 


[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [23]:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b)) 
print(np.where(np.intersect1d(a,b)))

[2 4]
(array([0, 1]),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [35]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
mask = names != 'Will'
print(mask)
data[mask]

[ True  True False  True False  True  True]


array([[-0.89291637,  0.20702363, -1.16883045, -0.42105681],
       [-0.02000732,  1.05626202,  1.72907753,  1.11260834],
       [-0.56947117,  1.41869415,  0.61715815, -2.42934804],
       [ 0.04119726, -1.92477234,  1.6805581 ,  1.24727536],
       [ 0.84593332, -0.19162985, -0.17031969,  0.51530365]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [24]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
mask = (names != 'Will') & (names != 'Joe')
print(mask)
data[mask]

[ True False False  True False False False]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],dtype= 'f')


newarr = arr.reshape(5,3)

print(newarr)


[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]


,,32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],dtype= 'f')


newarr = arr.reshape(2, 2, 4)

print(newarr)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]


33. Swap axes of the array you created in Question 32

In [27]:
np.swapaxes(newarr,1,2)

array([[[ 1.,  5.],
        [ 2.,  6.],
        [ 3.,  7.],
        [ 4.,  8.]],

       [[ 9., 13.],
        [10., 14.],
        [11., 15.],
        [12., 16.]]], dtype=float32)

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [28]:
arr = np.random.rand(10)
sqrt_arr = np.sqrt(arr) # https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html
sqrt_arr[sqrt_arr < .5] = 0
sqrt_arr

array([0.79369011, 0.62207439, 0.62815671, 0.95115426, 0.89966432,
       0.56782034, 0.        , 0.        , 0.73985989, 0.53470863])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [29]:
x = np.random.rand(12)
y = np.random.rand(12)
results = np.array([x.max(), y.max()])
print(x)
print('---------------------------------------------')
print(y)
print('---------------------------------------------')
print('Array of Max Numbers of Both Arrays',results)

[0.67424038 0.60303047 0.65500278 0.55012475 0.48859985 0.19300431
 0.77422531 0.88476062 0.18004021 0.74136581 0.83432977 0.32949787]
---------------------------------------------
[0.48251251 0.9741837  0.0421296  0.16885947 0.65830864 0.58985637
 0.28092587 0.51380953 0.67194777 0.33673584 0.43093966 0.31131249]
---------------------------------------------
Array of Max Numbers of Both Arrays [0.88476062 0.9741837 ]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unq_arr = np.unique(names)
print(unq_arr)

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [31]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

result = np.setdiff1d(a, b)
print(result)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [32]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
deletedColumnArray = np.delete(sampleArray, 1,1)
newColumn = np.array([[10,10,10]])
Result = np.insert(deletedColumnArray,1, newColumn,1)
Result

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [33]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x, y)  
x.dot(y) 
x @ y 

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [34]:
arr = np.random.rand(20)
print("Random number")
print(arr)

print("Cumlative sum of random number")
print(np.cumsum(arr))

Random number
[0.05172094 0.98834383 0.61257226 0.93021194 0.25636365 0.76395895
 0.63132104 0.53260332 0.90715956 0.83144288 0.52628331 0.07652917
 0.32313446 0.42391867 0.15925806 0.66406169 0.24667796 0.64729456
 0.03416639 0.50443525]
Cumlative sum of random number
[ 0.05172094  1.04006477  1.65263703  2.58284897  2.83921262  3.60317158
  4.23449261  4.76709593  5.67425549  6.50569837  7.03198168  7.10851085
  7.43164531  7.85556397  8.01482203  8.67888372  8.92556167  9.57285623
  9.60702262 10.11145786]
